// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEpTQZvy-FGUMB2bJhvB-ylZOWGk965QM',
    appId: '1:792926617532:web:3b73e4f35807039afaf5b9',
    messagingSenderId: '792926617532',
    projectId: 'ecomerce-getx',
    authDomain: 'ecomerce-getx.firebaseapp.com',
    storageBucket: 'ecomerce-getx.firebasestorage.app',
    measurementId: 'G-2NC9RCZ16G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYbdIC4Vf8_gsoVsaNwDHUQ5CV7IvD2tU',
    appId: '1:792926617532:android:f851c282403b0b71faf5b9',
    messagingSenderId: '792926617532',
    projectId: 'ecomerce-getx',
    storageBucket: 'ecomerce-getx.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbHwnlcqTjrUnmGwVahCASnizGgdBR8Eg',
    appId: '1:792926617532:ios:b4e8843a0be08e51faf5b9',
    messagingSenderId: '792926617532',
    projectId: 'ecomerce-getx',
    storageBucket: 'ecomerce-getx.firebasestorage.app',
    iosClientId: '792926617532-m4385jgr3f0l3d21jhdd3r6jb3mqvjid.apps.googleusercontent.com',
    iosBundleId: 'com.fongsy.heang',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbHwnlcqTjrUnmGwVahCASnizGgdBR8Eg',
    appId: '1:792926617532:ios:5813f4b79511c184faf5b9',
    messagingSenderId: '792926617532',
    projectId: 'ecomerce-getx',
    storageBucket: 'ecomerce-getx.firebasestorage.app',
    iosClientId: '792926617532-pvc2lsmgk3j0n2t958qa56cj3lsjshq7.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEpTQZvy-FGUMB2bJhvB-ylZOWGk965QM',
    appId: '1:792926617532:web:cbd90b3d8e29c046faf5b9',
    messagingSenderId: '792926617532',
    projectId: 'ecomerce-getx',
    authDomain: 'ecomerce-getx.firebaseapp.com',
    storageBucket: 'ecomerce-getx.firebasestorage.app',
    measurementId: 'G-HTYWDM38PG',
  );
}
